services:
  db:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "1234:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql